version: '3.6'

services:
  postgres:
   # build the image from Dockerfile
    build:
      context: ${PWD}
    networks:
      - default
    volumes:
      - ./app:/usr/src/app/app
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 5432:5432

